version: 2.1

jobs:
  build-docker:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: |
            docker build -t capstone .
            docker save -o docker_image capstone
      - persist_to_workspace:
          root: .
          paths:
            - docker_image

  test-docker:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: docker run
          command: |
            docker load -i workspace/docker_image
            docker run -p 8000:80 capstone
      - run:
          name: test docker
          command: |
            curl localhost:80
  upload-docker:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: docker upload
          command: |
            docker tag capstone tomsharp12/capstone
            docker push tomsharp12/capstone
  deploy-network:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: deploy network
          command: |
            yum -y install tar gzip
            aws cloudformation create-stack \
              --stack-name udacity-capstone-network \
              --template-body file://infra/network/network.yml \
              --parameters file://infra/network/network.json \
              --region=us-east-1 
  deploy-servers:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: deploy network
          command: |
            yum -y install tar gzip
            aws cloudformation create-stack \
              --stack-name udacity-capstone-servers \
              --template-body file://infra/servers/servers.yml \
              --parameters file://infra/servers/servers.json \
              --region=us-east-1 

workflows:
  default:
    jobs:
      - build-docker
      - test-docker:
          requires: [build-docker]
      - upload-docker:
          requires: [test-docker]
      - deploy-network:
          requires: []
      - deploy-servers:
          requires: [upload-docker, deploy-network]